version: '3'

volumes:
  static:
  pg_data:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    container_name: foodgram-frontend
    image: seno404star/frontend_foodgram
    command: cp -r /app/build/. /app/frontend_static/
    volumes:
      - static:/app/frontend_static
  backend:
    container_name: foodgram-backend
    env_file: .env
    image: seno404star/backend_foodgram
    volumes:
      - static:/app/web
      - media:/app/media
    depends_on:
      - db
    command: >
      /bin/bash -c "
        python manage.py collectstatic --noinput
        cp -r /app/static/. web/static &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('$ADMIN_USERNAME', '$ADMIN_EMAIL', '$ADMIN_PASSWORD')\" | python manage.py shell &&
        gunicorn --bind 0.0.0.0:8000 backend_foodgram.wsgi
        python manage.py load_csv
      "
  gateway:
    env_file: .env
    image: seno404star/gateway_foodgram
    volumes:
      - static:/web
      - media:/web/media
    ports:
      - 8000:80